version: 2

jobs:
  build:
    docker:
      - image: rustrpm/ci:20180609.0 # bump cache keys when modifying this

    steps:
      - checkout
      - restore_cache:
          key: cache-20180609.0 # bump save_cache key below too
      - run:
          name: rustfmt
          command: |
            cargo +$RUST_NIGHTLY_VERSION fmt --version
            cargo +$RUST_NIGHTLY_VERSION fmt --all -- --check
      - run:
          name: clippy
          command: |
            cargo +$RUST_NIGHTLY_VERSION clippy --version
            cargo +$RUST_NIGHTLY_VERSION clippy --all
      - run:
          name: build
          command: |
            rustc --version
            cargo --version
            cargo build --all
      - run:
          name: test
          command: |
            rustc --version
            cargo --version
            cargo test --all
      - save_cache:
          key: cache-20180609.0 # bump restore_cache key above too
          paths:
            - "~/.cargo"
            - "./target"
